
/***************************************************
 * Generated by SVG Artista on 8/29/2019, 1:31:49 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 6.965676784515381px;
    stroke-dasharray: 6.965676784515381px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 6.965676784515381px;
    stroke-dasharray: 6.965676784515381px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 1, 1);
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 1, 1);
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
                       animate-svg-fill-1 1.5s ease-in-out 0.8s both;
          animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
               animate-svg-fill-1 1.5s ease-in-out 0.8s both;
}

@-webkit-keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 2198.513427734375px;
    stroke-dasharray: 2198.513427734375px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 2198.513427734375px;
    stroke-dasharray: 2198.513427734375px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 1, 1);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 1, 1);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s both,
                       animate-svg-fill-2 1.5s ease-in-out 1.3s both;
          animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s both,
               animate-svg-fill-2 1.5s ease-in-out 1.3s both;
}

@-webkit-keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 3665.497802734375px;
    stroke-dasharray: 3665.497802734375px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 3665.497802734375px;
    stroke-dasharray: 3665.497802734375px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 1, 1);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 1, 1);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.4s both,
                       animate-svg-fill-3 1.5s ease-in-out 1.8s both;
          animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.4s both,
               animate-svg-fill-3 1.5s ease-in-out 1.8s both;
}

@-webkit-keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 2080.82861328125px;
    stroke-dasharray: 2080.82861328125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 2080.82861328125px;
    stroke-dasharray: 2080.82861328125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(254, 226, 9);
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(254, 226, 9);
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-stroke-4 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6000000000000001s both,
                       animate-svg-fill-4 1.5s ease-in-out 2.3s both;
          animation: animate-svg-stroke-4 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6000000000000001s both,
               animate-svg-fill-4 1.5s ease-in-out 2.3s both;
}

@-webkit-keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 2376.00048828125px;
    stroke-dasharray: 2376.00048828125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 2376.00048828125px;
    stroke-dasharray: 2376.00048828125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(254, 226, 9);
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(254, 226, 9);
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-stroke-5 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both,
                       animate-svg-fill-5 1.5s ease-in-out 2.8s both;
          animation: animate-svg-stroke-5 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both,
               animate-svg-fill-5 1.5s ease-in-out 2.8s both;
}

@-webkit-keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 6.965676784515381px;
    stroke-dasharray: 6.965676784515381px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 6.965676784515381px;
    stroke-dasharray: 6.965676784515381px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 1, 1);
  }
}

@keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 1, 1);
  }
}

.svg-elem-6 {
  -webkit-animation: animate-svg-stroke-6 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both,
                       animate-svg-fill-6 1.5s ease-in-out 3.3s both;
          animation: animate-svg-stroke-6 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both,
               animate-svg-fill-6 1.5s ease-in-out 3.3s both;
}

@-webkit-keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 2198.513427734375px;
    stroke-dasharray: 2198.513427734375px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 2198.513427734375px;
    stroke-dasharray: 2198.513427734375px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

.svg-elem-7 {
  -webkit-animation: animate-svg-stroke-7 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both,
                       animate-svg-fill-7 1.5s ease-in-out 3.8s both;
          animation: animate-svg-stroke-7 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both,
               animate-svg-fill-7 1.5s ease-in-out 3.8s both;
}

@-webkit-keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 3665.497802734375px;
    stroke-dasharray: 3665.497802734375px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 3665.497802734375px;
    stroke-dasharray: 3665.497802734375px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

.svg-elem-8 {
  -webkit-animation: animate-svg-stroke-8 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both,
                       animate-svg-fill-8 1.5s ease-in-out 4.3s both;
          animation: animate-svg-stroke-8 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both,
               animate-svg-fill-8 1.5s ease-in-out 4.3s both;
}

@-webkit-keyframes animate-svg-stroke-9 {
  0% {
    stroke-dashoffset: 2080.82861328125px;
    stroke-dasharray: 2080.82861328125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-9 {
  0% {
    stroke-dashoffset: 2080.82861328125px;
    stroke-dasharray: 2080.82861328125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

.svg-elem-9 {
  -webkit-animation: animate-svg-stroke-9 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both,
                       animate-svg-fill-9 1.5s ease-in-out 4.8s both;
          animation: animate-svg-stroke-9 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both,
               animate-svg-fill-9 1.5s ease-in-out 4.8s both;
}

@-webkit-keyframes animate-svg-stroke-10 {
  0% {
    stroke-dashoffset: 2376.00048828125px;
    stroke-dasharray: 2376.00048828125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-10 {
  0% {
    stroke-dashoffset: 2376.00048828125px;
    stroke-dasharray: 2376.00048828125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

.svg-elem-10 {
  -webkit-animation: animate-svg-stroke-10 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both,
                       animate-svg-fill-10 1.5s ease-in-out 5.3s both;
          animation: animate-svg-stroke-10 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both,
               animate-svg-fill-10 1.5s ease-in-out 5.3s both;
}